import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { compile } from "./lib/compile.mjs";
import { ROOT } from "./lib/env.mjs";

const v2 = compile("QuorumVault.sol", "QuorumVault");
const v3 = compile("QuorumVaultV3.sol", "QuorumVaultV3");
const brain = compile("QuorumBrain.sol", "QuorumBrain");
const out = `// GENERATED by scripts/build-abis.mjs — do not edit.
export const quorumVaultAbi = ${JSON.stringify(v2.abi)} as const;
export const quorumVaultBytecode = ${JSON.stringify(v2.bytecode)} as const;
export const quorumVaultV3Abi = ${JSON.stringify(v3.abi)} as const;
export const quorumVaultV3Bytecode = ${JSON.stringify(v3.bytecode)} as const;
export const quorumBrainAbi = ${JSON.stringify(brain.abi)} as const;
export const quorumBrainBytecode = ${JSON.stringify(brain.bytecode)} as const;
`;
writeFileSync(join(ROOT, "src/somnia/vaultAbi.ts"), out);
console.log("wrote src/somnia/vaultAbi.ts (v2 + v3 + brain)");
