import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { compile } from "./lib/compile.mjs";
import { ROOT } from "./lib/env.mjs";

const { abi, bytecode } = compile("QuorumVault.sol", "QuorumVault");
const out = `// GENERATED by scripts/build-abis.mjs — do not edit.
export const quorumVaultAbi = ${JSON.stringify(abi)} as const;
export const quorumVaultBytecode = ${JSON.stringify(bytecode)} as const;
`;
writeFileSync(join(ROOT, "src/somnia/vaultAbi.ts"), out);
console.log("wrote src/somnia/vaultAbi.ts");
